"""comment property added to Issue class

Revision ID: 15db8e210f58
Revises: dc453bcdf37c
Create Date: 2016-11-23 12:30:39.588000

"""

# revision identifiers, used by Alembic.
revision = '15db8e210f58'
down_revision = 'dc453bcdf37c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('comment', sa.Text(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'comment')
    ### end Alembic commands ###
